name: rois
channels:
  - ome
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - expat=2.2.6
  - freetype=2.9.1
  - future=0.18.2
  - intel-openmp=2020.0
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - omero-py=5.6.2
  - openssl=1.1.1g
  - pillow=7.0.0
  - pip=20.0.2
  - python=3.6.10
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zeroc-ice36-python=3.6.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - attrs==19.3.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - idna==2.9
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - more-itertools==8.2.0
    - networkx==2.4
    - packaging==20.3
    - pluggy==0.13.1
    - py==1.8.1
    - pyparsing==2.4.7
    - pytest==5.4.1
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - requests==2.23.0
    - scikit-image==0.16.2
    - scipy==1.4.1
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - zipp==3.1.0

